### ISSUE TITLE
drop this module, it should be layers of mfext

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfcom#169]
the split between mfext and mfcom is historical and has no sense today since metwork framework is completly open source

Prerequisites:

- [x] move `synutil_c` into `mfutil_c`
- [x] move `synutil_lua` as an independent repository

**Comment by thefab** [comment]
we propose to use following layer names:

- `misc@mfext` (current `adm` content)
- `python3_misc@mfext`
- `python2_misc@mfext`

**Comment by thebaptiste** [comment]
Done
